### ISSUE TITLE
Error when "opening on GitHub"

### ISSUE THREAD

**Issue by adrienpessu** [agorapulse/pierrot#41] opened 2021-11-24 08:01 UTC
Hello dear maintainer,

I checked what PR are assigned to me and tried to open in github and I get this stacktrace : 

```
pierrot status user-review-requested:@me
Searching pull requests for 'user-review-requested:@me'!
========================================================================================================================
| agorapulse/xxxxxxxxxxxxxxx
------------------------------------------------------------------------------------------------------------------------
| BLOCKED    | xxxxxxxxxxxxx is upgraded to 2021.11.20.1628
------------------------------------------------------------------------------------------------------------------------
| ✓ build_n_test
ENTER=continue, q=quit, a=all, o=open on GitHub: o
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:197)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.System.loadLibrary(System.java:1871)
	at java.awt.Toolkit$3.run(Toolkit.java:1395)
	at java.awt.Toolkit$3.run(Toolkit.java:1393)
	at java.security.AccessController.doPrivileged(AccessController.java:87)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1425)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at java.awt.Desktop.isDesktopSupported(Desktop.java:328)
	at com.agorapulse.pierrot.cli.mixin.SearchMixin.open(SearchMixin.java:157)
	at java.util.Optional.ifPresent(Optional.java:183)
	at com.agorapulse.pierrot.cli.mixin.SearchMixin.paginate(SearchMixin.java:138)
	at com.agorapulse.pierrot.cli.mixin.SearchMixin.lambda$searchPullRequests$3(SearchMixin.java:90)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.agorapulse.pierrot.cli.mixin.SearchMixin.searchPullRequests(SearchMixin.java:90)
	at com.agorapulse.pierrot.cli.StatusCommand.run(StatusCommand.java:64)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.agorapulse.pierrot.cli.PierrotCommand.execute(PierrotCommand.java:115)
	at com.agorapulse.pierrot.cli.PierrotCommand.main(PierrotCommand.java:88)

```

**Comment by musketyr** [comment] 2021-11-24 08:17
duplicate of #40 😉

**Closed by musketyr** 2021-11-24 08:17 UTC
